export const LOAD_SUPERHEROES = "LOAD_SUPERHEROES";
export const LOAD_SUPERHEROES_SUCCESS = "LOAD_SUPERHEROES_SUCCESS";
export const LOAD_SUPERHERO_SUCCESS = "LOAD_SUPERHER_SUCCESS";
export const ADD_SUPERHERO_SUCCESS = "ADD_SUPERHERO_SUCCESS";
